import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    // เปลี่ยนมาใช้ suppressHydrationWarning (ตัวพิมพ์ใหญ่ H และ W)
    <html lang="en" suppressHydrationWarning>
      <body className="...">
        {children}
      </body>
    </html>
  );
}
